### ISSUE TITLE
Very cool project!

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monokex#1]
No issue. I just wanted to say that this is a very cool project.

**Comment by LoupVaillant** [comment]
Thanks!

By the way, do you have any opinion on the generated protocols themselves? I have [reasons to believe it works](https://github.com/LoupVaillant/Monocypher-Handshake/blob/master/SECURITY_ANALYSIS.md#key-derivation), but I have yet to have external feedback on this. (Long story short, I use HChacha20 instead of a general purpose hash to derive keys from shared secrets).
