### ISSUE TITLE
Monokex assumes that ordering of tokens in same message matters

### ISSUE THREAD

**Issue by nadimkobeissi** [LoupVaillant/Monokex#2]
Please see this: https://github.com/SymbolicSoft/noiseexplorer/issues/23

**Comment by LoupVaillant** [comment]
Okay, after a significant amount of digging…

…this is not a bug. Order _does_ matter. Monokex does not sort the token before processing them for code generation, so the wrong order would cause it to generate broken code (with undefined behaviour like uninitialised reads).

And it turns out Noise Explorer has the [same issue](https://github.com/SymbolicSoft/noiseexplorer/issues/24). Except instead of rejecting the pattern, it generates broken Rust code.
